// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Car struct {
	ID         int64
	Name       string
	Price      float64
	StartAt    sql.NullTime
	EndAt      sql.NullTime
	OwnerID    int64
	DistrictID int64
}

type District struct {
	ID   int64
	Name string
}

type User struct {
	ID        int64
	Username  string
	Firstname string
	Lastname  string
	Passhash  string
	Phone     string
	Email     string
}
